### ISSUE TITLE
Error when generating a helper test

### ISSUE THREAD

**Issue by erichonkanen** [kimroen/ember-cli-coffeescript#113]
Hello,

I got an error while generating a helper via `ember generate helper foo-pa`

```
ember generate helper foo-pa
installing helper
  create app/helpers/foo-pa.coffee
installing helper-test
  create tests/unit/helpers/foo-pa-test.coffee
dependencyDepth is not defined (Error in blueprint template: /Users/eric/Projects/craft/app-web/node_modules/ember-cli-coffeescript/blueprints/helper-test/files/tests/unit/helpers/__name__-test.coffee)
ReferenceError: dependencyDepth is not defined (Error in blueprint template: /Users/eric/Projects/craft/app-web/node_modules/ember-cli-coffeescript/blueprints/helper-test/files/tests/unit/helpers/__name__-test.coffee)
  at eval (<anonymous>:10:11)
  at processTemplate (/Users/eric/Projects/craft/app-web/node_modules/ember-cli/lib/models/file-info.js:20:36)
  at /Users/eric/Projects/craft/app-web/node_modules/ember-cli/lib/models/file-info.js:97:20
  at lib$rsvp$$internal$$tryCatch (/Users/eric/Projects/craft/app-web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/eric/Projects/craft/app-web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
  at lib$rsvp$$internal$$publish (/Users/eric/Projects/craft/app-web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
  at lib$rsvp$asap$$flush (/Users/eric/Projects/craft/app-web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)
```

**Comment by erichonkanen** [comment]
edit: updating to latest 1.14.0 seems to resolve this
