### ISSUE TITLE
Blueprints do not work with new ember-cli

### ISSUE THREAD

**Issue by mriska** [kimroen/ember-cli-coffeescript#146]
```shell
› ember -v
ember-cli: 2.13.2
node: 7.7.4
os: darwin x64

› ember new route-test

...

› cd route-test

› ember generate route foo
installing route
  create app/routes/foo.js
  create app/templates/foo.hbs
updating router
  add route foo
installing route-test
  create tests/unit/routes/foo-test.js

› ember install ember-cli-coffeescript
NPM: Installed ember-cli-coffeescript
Installed addon package.

› ember generate route bar
installing route
Cannot read property 'moduleName' of undefined
TypeError: Cannot read property 'moduleName' of undefined
  at __name__ (/Users/mriska/route-test/node_modules/ember-source/blueprints/route/index.js:35:30)
  at fileMapValues.map.token (/Users/mriska/route-test/node_modules/ember-cli/lib/models/blueprint.js:633:50)
  at Array.map (native)
  at Class.generateFileMap (/Users/mriska/route-test/node_modules/ember-cli/lib/models/blueprint.js:633:37)
  at Promise.then.customLocals (/Users/mriska/route-test/node_modules/ember-cli/lib/models/blueprint.js:827:26)
  at tryCatch (/Users/mriska/route-test/node_modules/rsvp/dist/rsvp.js:539:12)
  at invokeCallback (/Users/mriska/route-test/node_modules/rsvp/dist/rsvp.js:554:13)
  at /Users/mriska/route-test/node_modules/rsvp/dist/rsvp.js:629:16
  at flush (/Users/mriska/route-test/node_modules/rsvp/dist/rsvp.js:2414:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by mriska** [comment]
In order to **temporarily** work around these issues you can make a change in the file:
`node_modules/ember-source/blueprints/route/index.js`

Change any instance of `options.locals.moduleName` to `options.dasherizedModuleName` and it should work.

**Comment by perlun** [comment]
I am seeing the exact same problem. Has anyone had the chance of investigating this further?

**Comment by alexphys** [comment]
Same here
```
$ ember -v
ember-cli: 2.16.2
node: 7.10.0
os: linux x64


$ ember g route foo/bar
installing route
Cannot read property 'moduleName' of undefined
TypeError: Cannot read property 'moduleName' of undefined
  at __name__ (.../node_modules/ember-source/blueprints/route/index.js:35:30)
  at fileMapValues.map.token (.../node_modules/ember-cli/lib/models/blueprint.js:633:50)
  at Array.map (native)
  at Class.generateFileMap (.../node_modules/ember-cli/lib/models/blueprint.js:633:37)
  at Promise.then.customLocals (.../node_modules/ember-cli/lib/models/blueprint.js:827:26)
  at tryCatch (.../node_modules/rsvp/dist/rsvp.js:525:12)
  at invokeCallback (.../node_modules/rsvp/dist/rsvp.js:538:13)
  at .../node_modules/rsvp/dist/rsvp.js:606:14
  at flush (.../node_modules/rsvp/dist/rsvp.js:2400:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by 1c7** [comment]
Same here


![image](https://user-images.githubusercontent.com/1804755/38420195-8cac6acc-39d5-11e8-9769-c21383e3dbee.png)
