### ISSUE TITLE
Cannot find module 'ember-cli/lib/ext/promise' on "ember help g"

### ISSUE THREAD

**Issue by olleolleolle** [kimroen/ember-cli-coffeescript#150]
I'm using ember-cli 3.1 and Ember.js 3.0.

This is the failure when I list generators:

<details>

```
$ ember help g
(...snipped DEPRECATION warnings...)

Requested ember-cli commands:

ember generate <blueprint> <options...>
  Generates new code from blueprints.
  aliases: g
  --dry-run (Boolean) (Default: false)
    aliases: -d
  --verbose (Boolean) (Default: false)
    aliases: -v
  --pod (Boolean) (Default: false)
    aliases: -p
  --classic (Boolean) (Default: false)
    aliases: -c
  --dummy (Boolean) (Default: false)
    aliases: -dum, -id
  --in-repo-addon (String) (Default: null)
    aliases: --in-repo <value>, -ir <value>

Cannot find module 'ember-cli/lib/ext/promise'


Stack Trace and Error Report: /var/folders/c3/chrhhctn30z1jhqstpp7bt480000gn/T/error.dump.61d27fb76c7fae2b1616cbf81d9d694d.log
```

And in the stack trace:

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Cannot find module 'ember-cli/lib/ext/promise'
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module 'ember-cli/lib/ext/promise'
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module 'ember-cli/lib/ext/promise'
  at Function.Module._resolveFilename (module.js:547:15)
  at Function.Module._load (module.js:474:25)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/Users/olle/work/my-app/node_modules/ember-cli-coffeescript/blueprints/resource/index.js:2:18)

```

<summary>Output of: $ ember help g</summary>

</details>

## Proposed fix

Release a new version.

## Workaround

**Current workaround**: refer to the master version in `package.json`:

```diff
-    "ember-cli-coffeescript": "^1.16.1",
+    "ember-cli-coffeescript": "kimroen/ember-cli-coffeescript#b931766332dc8ee7630715ddcb93c77351e506a4",
```

My guess: those things which were deprecation warnings before, they're removed now.

**Comment by olleolleolle** [comment]
Is it time to release a new version?

**Comment by mriska** [comment]
Hi @kimroen, is it possible to release a version `1.16.2` from master? The generators do not work in the current version with ember-cli 3.0.0 or greater. I know that CoffeeScript usage is diminishing, but there are still a bunch of us that are using your excellent addon and we want to keep using the latest build tools.

**Comment by olleolleolle** [comment]
**Current workaround**: refer to the master version in `package.json`:

```diff
-    "ember-cli-coffeescript": "^1.16.1",
+    "ember-cli-coffeescript": "kimroen/ember-cli-coffeescript#b931766332dc8ee7630715ddcb93c77351e506a4",
```
