### ISSUE TITLE
Ember-cli build fails with 'file already exists' error 

### ISSUE THREAD

**Issue by youroff** [kimroen/ember-cli-coffeescript#92]
Keep getting this error after an attempt to install some package. Not sure if it has to do with ember-cli-coffeescript. Here's the trace:

```
EEXIST, file already exists '/Users/youroff/Documents/projects/ember/try/client/tmp/coffee_script_filter-tmp_dest_dir-hVmW4TxL.tmp/autocloud/routes/application.js'
Error: EEXIST, file already exists '/Users/youroff/Documents/projects/ember/try/client/tmp/coffee_script_filter-tmp_dest_dir-hVmW4TxL.tmp/autocloud/routes/application.js'
  at Error (native)
  at Object.fs.symlinkSync (fs.js:848:18)
  at symlink (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/symlink-or-copy/index.js:82:14)
  at symlinkOrCopySync (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/symlink-or-copy/index.js:58:5)
  at /Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/index.js:45:11
  at /Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/promise-map-series/index.js:11:14
  at lib$rsvp$$internal$$tryCatch (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/youroff/Documents/projects/ember/try/client/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/node_modules/rsvp/dist/rsvp.js:1198:9)
  at process._tickCallback (node.js:355:11)
```

It looks like as if I had two routes (i.e. application.js and application.coffee) defined, but it's not. There's only one file in routes folder.

**Comment by kimroen** [comment]
Hmm, the only other thing I can think of is if the package you have installed has an `application.js` route defined and is trying to merge that in to your project.

If that is the case, there is unfortunately nothing to do about it in your project as far as I know, other than to not use coffeescript for this file.

This is the same as this other issue: https://github.com/kimroen/ember-cli-coffeescript/issues/87 I'd love some feedback or suggestions there if you have the capacity.

Thanks, and sorry.

**Comment by youroff** [comment]
Yes, you were right. I just realized that it was simple-auth package. Rewriting that one file in JS would work, thank you!
