### ISSUE TITLE
Not generating coffeescript blueprints for routes or components

### ISSUE THREAD

**Issue by dchersey** [kimroen/ember-cli-coffeescript#97]
I've just installed the plugin, and when I generate a pod or a component I am getting javascript blueprints for the pod itself, but coffeescript for the tests. 

I tried adding 
```javascript
ENV.coffeeOptions = {
  blueprints: true
}
```
to try to force it but it is still not happening.  Is there anything else I was supposed to do besides `ember install ember-cli-emberscript` ?

**Comment by kimroen** [comment]
That's curious, no - just installing it should be quite sufficient.

You can try running this command to see your blueprints - it sounds like something else is providing blueprints and they are getting higher priority:

```
ember generate --help
```

(I think that's the command, on my phone so can't check)

**Comment by kimroen** [comment]
By the way:

> to try to force it but it is still not happening. Is there anything else I was supposed to do besides `ember install ember-cli-emberscript`?

Just to be sure, you mean `ember install ember-cli-coffeescript` here, right?

**Comment by dchersey** [comment]
Ok will do (on my phone too).  Might be emblem-cli; If that's the case is there anything I can configure to resolve the dependency?

**Comment by kimroen** [comment]
Not that I can think of right now. I think adding that to this would solve it: https://github.com/kimroen/ember-cli-coffeescript/blob/master/package.json#L38

**Comment by dchersey** [comment]
Yes!! Was playing with ember script first and still had it on the brain.  I uninstalled that one as it seems out of date.

**Comment by dchersey** [comment]
Ok, will try that and let you know.

**Comment by zkwentz** [comment]
I tried this myself, doesn't appear to resolve the issue.

**Comment by kimroen** [comment]
> looks like the component generator isn't showing up?

No, but it should show up in the section of the addon that is also providing a component blueprint and overwriting the one from this addon.

**Comment by davearel** [comment]
I'm having an issue here as well. The route generator seems to be defaulting to the ember-cli blueprint. Despite the fact I have `ember-cli-coffeescript` installed. Other generators are working fine.

```
$ ember g route register
version: 1.13.14
installing route
  create app/routes/register.js
  create app/templates/register.emblem
ENOENT: no such file or directory, open '/Users/dave/code/ide/app/router.js'
Error: ENOENT: no such file or directory, open '/Users/dave/code/ide/app/router.js'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.fs.readFileSync (fs.js:397:15)
  at writeRoute (/Users/dave/code/ide/node_modules/ember-cli/blueprints/route/index.js:116:19)
  at Class.updateRouter (/Users/dave/code/ide/node_modules/ember-cli/blueprints/route/index.js:95:5)
  at Class.module.exports.afterInstall (/Users/dave/code/ide/node_modules/ember-cli/blueprints/route/index.js:78:18)
  at Class.module.exports.afterInstall (/Users/dave/code/ide/node_modules/ember-cli-emblem/blueprints/route/index.js:42:40)
  at Class.module.exports.afterInstall (/Users/dave/code/ide/node_modules/ember-cli-emblem/blueprints/route/index.js:42:40)
  at lib$rsvp$$internal$$tryCatch (/Users/dave/code/ide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/dave/code/ide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (/Users/dave/code/ide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
  at lib$rsvp$asap$$flush (/Users/dave/code/ide/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)
```

**Comment by zkwentz** [comment]
It's a conflict between emblem and coffeescript. They both override the
same generator, and it depends on which is defined lower in package.json,
for which takes precedence.

**Comment by kimroen** [comment]
> It's a conflict between emblem and coffeescript. They both override the
> same generator, and it depends on which is defined lower in package.json,
> for which takes precedence.

Thanks, that's very helpful information.

**Comment by zkwentz** [comment]
Sure thing, I haven't found a workaround myself, but then again I haven't looked hard either, at the moment I just run `mv ....{hbs,emblem}`, after each generate command.

**Comment by davearel** [comment]
This might be something that should be addressed in Ember-CLI, or even Emblem. I opened a ticket in Emblem to make them aware of the issue.

**Comment by kimroen** [comment]
As you suggest, this is more of a fundemental ember-CLI problem, also related to https://github.com/kimroen/ember-cli-coffeescript/issues/87

I'm excited to see if the proposed module changes will make this better - something needs to change with blueprints to accommodate those changes.

**Comment by ralmidani** [comment]
We were running into this issue, and found a simple workaround: delete the blueprints folder in ember-cli-emblem. This means you will have rename the .hbs files to .emblem and remove the double curly braces inside the files, but it is easier than having to refactor .js files to .coffee.

This is, of course, unsustainable in the long term, since updates may bring the blueprints folder back. But if you just need to move on with development, it is the best option among many unattractive ones.
